name: display_data_folder_content
on: [push]
jobs:
  generate-profile:
    runs-on: ubuntu-latest

    steps:       
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Checkout submodules
        uses: actions/git-checkout-submodule-action@master
      - name: ls
        run: ls specifications