name: display_data_folder_content
on: [push]
jobs:
  generate-profile:
    runs-on: ubuntu-latest

    steps:       
      - name: Checkout
        uses: actions/checkout@v3
        submodules: recursive

      - name: ls
        run: ls specifications